FROM python:3.13-slim

RUN apt-get update && apt-get install -y \
        iputils-ping \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src

# sleep 3 → dá tempo do recebe subir e entrar no recvfrom antes dos pacotes chegarem
CMD ["sh", "-c", "sleep 3 && python3 -u client.py"]