FROM python:3.13-slim

RUN apt-get update && apt-get install -y \
        tcpdump \
        iputils-ping \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src

# -u = unbuffered stdout so logs appear in real time
CMD ["python3", "-u", "server.py"]